name: Databricks CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Stage 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    # Step 3: 安装 Databricks CLI
    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    # Step 4: 配置 Databricks CLI
    - name: Configure Databricks CLI
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks configure --token <<EOF
        $DATABRICKS_HOST
        $DATABRICKS_TOKEN
        EOF

    # Step 5: 上传脚本到 Databricks Workspace
    - name: Upload script to Databricks
      run: |
        databricks workspace import ./qc_wine.py /Users/qc57@duke.edu/Data-Pipeline-with-Databricks/qc_wine.py --overwrite --language PYTHON

    # Step 6: 在 Databricks 中运行脚本
    - name: Run script on Databricks
      run: |
        databricks jobs run-now --job-id ${{ secrets.DATABRICKS_JOB_ID }}

  # Stage 2: Test
  test:
    runs-on: ubuntu-latest
    needs: build  # 依赖 build 阶段
    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        pip install pytest

    # Step 4: 运行测试
    - name: Run tests
      run: |
        pytest qc_wine.py || python -m py_compile qc_wine.py

  # Stage 3: Lint
  lint:
    runs-on: ubuntu-latest
    needs: build  # 依赖 build 阶段
    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Step 3: 安装 flake8
    - name: Install flake8
      run: |
        pip install flake8

    # Step 4: 检查代码风格
    - name: Lint code with flake8
      run: |
        flake8 qc_wine.py


